image: openkbs/jdk-mvn-py3

stages:
  - build
  - run

build-python:
  stage: build
  artifacts:
    untracked: true
    expire_in: 1h
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - mv gitlab/config.py ./
    - mv gitlab/config.yaml ./

build-test:
  stage: build
  artifacts:
    untracked: true
    expire_in: 1h
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/AvocadoCore/Server-Web/functional-testing-web.git
    - cd functional-testing-web
    - rm -rf .git
    - mvn install
    - mv target/functional-testing-1.jar ../
    - cd ..
    - rm -rf functional-testing-web

build-npm:
  stage: build
  artifacts:
    untracked: true
    expire_in: 1h
  script:
    - mv gitlab/config.yaml ./
    - cd static
    - sudo npm install --unsafe-perm
    - node --max_old_space_size=8192 node_modules/webpack/bin/webpack.js --progress --config webpack.config.js

run-test:
  stage: run
  services:
  - mysql:5.5
  variables:
    MYSQL_DATABASE: "dev"
    MYSQL_ROOT_PASSWORD: "root"
  script:
    - sudo apt-get update -q
    - sudo apt-get install -qqy --no-install-recommends mysql-client
    - sudo apt-get install -qqy --no-install-recommends screen
    - wget https://gist.githubusercontent.com/nirmalvett/c27e73723f6f1075609aa637c88a808e/raw/5d8704b87d6c4e2bd4cb96250a8c991c0424f341/install.sh
    - sudo bash install.sh
    - sudo mv ~/chromedriver .
    - sudo chmod +x chromedriver
    - screen -d -m bash -c "./chromedriver --url-base=/wd/hub"
    - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}" < gitlab/ci_test.sql
    - bash -c "bash -c 'source venv/bin/activate; python3 app.py' & bash -c 'sleep 10; java -DavoUrl="http://127.0.0.1:5000" -Dwebdriver.chrome.driver="chromedriver" -jar functional-testing-1.jar SpecOrder'"
