"""added lesson content table

Revision ID: 0cc4d5d133fc
Revises: 451bb9c61df1
Create Date: 2019-09-07 14:02:32.006431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc4d5d133fc'
down_revision = '451bb9c61df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_content',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TAG', sa.Integer(), nullable=False),
    sa.Column('LESSON_CONTENT', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['TAG'], ['TAG.TAG'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_content')
    # ### end Alembic commands ###
