"""got rid of user_lesson

Revision ID: 0fd389094d2b
Revises: 0cc4d5d133fc
Create Date: 2019-09-08 21:49:30.442116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fd389094d2b'
down_revision = '0cc4d5d133fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lesson')
    op.add_column('LESSON', sa.Column('CLASS', sa.Integer(), nullable=False))
    op.drop_constraint('LESSON_ibfk_2', 'LESSON', type_='foreignkey')
    op.create_foreign_key(None, 'LESSON', 'CLASS', ['CLASS'], ['CLASS'])
    op.drop_column('LESSON', 'USER')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LESSON', sa.Column('USER', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'LESSON', type_='foreignkey')
    op.create_foreign_key('LESSON_ibfk_2', 'LESSON', 'USER', ['USER'], ['USER'])
    op.drop_column('LESSON', 'CLASS')
    op.create_table('user_lesson',
    sa.Column('USER_LESSON', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('USER', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('LESSON', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['LESSON'], ['LESSON.LESSON'], name='user_lesson_ibfk_1'),
    sa.ForeignKeyConstraint(['USER'], ['USER.USER'], name='user_lesson_ibfk_2'),
    sa.PrimaryKeyConstraint('USER_LESSON'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
